export const NavItems = [
  {
    id: 1,
    title: "Supernatural",
    path: "genre/supernatural",
    cName: "dropdown-link",
  },
  { id: 2, title: "Action", path: "genre/action", cName: "dropdown-link" },
  { id: 3, title: "Comedy", path: "genre/comedy", cName: "dropdown-link" },
  { id: 4, title: "Romance", path: "genre/romance", cName: "dropdown-link" },
  { id: 5, title: "Ecchi", path: "genre/ecchi", cName: "dropdown-link" },
  {
    id: 6,
    title: "Adventure",
    path: "genre/adventure",
    cName: "dropdown-link",
  },
  { id: 7, title: "Fantasy", path: "genre/fantasy", cName: "dropdown-link" },
  { id: 8, title: "Magic", path: "genre/magic", cName: "dropdown-link" },
  {
    id: 9,
    title: "Psychological",
    path: "genre/psychological",
    cName: "dropdown-link",
  },
  { id: 10, title: "Drama", path: "genre/drama", cName: "dropdown-link" },
  {
    id: 11,
    title: "Mystery",
    path: "genre/mystery",
    cName: "dropdown-link",
  },
  { id: 12, title: "Sci-Fi", path: "genre/sci-Fi", cName: "dropdown-link" },
  {
    id: 13,
    title: "Slice of Life",
    path: "genre/slice-of-life",
    cName: "dropdown-link",
  },
  { id: 14, title: "Yaoi", path: "genre/yaoi", cName: "dropdown-link" },
  { id: 15, title: "Horror", path: "genre/horror", cName: "dropdown-link" },
  {
    id: 16,
    title: "Thriller",
    path: "genre/thriller",
    cName: "dropdown-link",
  },
  {
    id: 17,
    title: "Shounen Ai",
    path: "genre/shounen-ai",
    cName: "dropdown-link",
  },
  {
    id: 18,
    title: "Gender Bender",
    path: "genre/gender-bender",
    cName: "dropdown-link",
  },
  { id: 19, title: "Sports", path: "genre/sports", cName: "dropdown-link" },
  { id: 20, title: "Yuri", path: "genre/yuri", cName: "dropdown-link" },
  {
    id: 21,
    title: "Shoujo Ai",
    path: "genre/shoujo-ai",
    cName: "dropdown-link",
  },
  { id: 22, title: "Mature", path: "genre/mature", cName: "dropdown-link" },
  {
    id: 23,
    title: "One Shot",
    path: "genre/one-shot",
    cName: "dropdown-link",
  },
  { id: 24, title: "Crime", path: "genre/crime", cName: "dropdown-link" },
];
